#%RAML 1.0 Trait

responses:
  400: 
    body:
      application/json:
        example:
          error: bad request
  404: 
    body:
      application/json:
        example:
          error: resource not found
